let POKEMON_TYPES = [
  "normal",
  "fighting",
  "flying",
  "poison",
  "ground",
  "rock",
  "bug",
  "ghost",
  "steel",
  "fire",
  "water",
  "grass",
  "electric",
  "psychic",
  "ice",
  "dragon",
  "dark",
  "fairy",
];

let POKEGENE_COST = [
  { value: "normal", cost: 5 },
  { value: "fighting", cost: 5 },
  { value: "flying", cost: 5 },
  { value: "poison", cost: 15 },
  { value: "ground", cost: 10 },
  { value: "rock", cost: 10 },
  { value: "bug", cost: 10 },
  { value: "ghost", cost: 15 },
  { value: "steel", cost: 15 },
  { value: "fire", cost: 15 },
  { value: "water", cost: 10 },
  { value: "grass", cost: 15 },
  { value: "electric", cost: 15 },
  { value: "psychic", cost: 10 },
  { value: "ice", cost: 10 },
  { value: "dragon", cost: 15 },
  { value: "dark", cost: 15 },
  { value: "fairy", cost: 5 },
];

let NO_IMAGE_NAME = [
  "sinistcha",
  "mimikyu-busted",
  "mimikyu-totem-busted",
  "koraidon-limited-build",
  "koraidon-sprinting-build",
  "koraidon-swimming-build",
  "koraidon-gliding-build",
  "miraidon-low-power-mode",
  "miraidon-drive-mode",
  "miraidon-aquatic-mode",
  "miraidon-glide-mode",
  "ursaluna-bloodmoon",
  "ogerpon-wellspring-mask",
  "ogerpon-hearthflame-mask",
  "ogerpon-cornerstone-mask",
];

module.exports = { POKEMON_TYPES, POKEGENE_COST, NO_IMAGE_NAME };
